name: expense_tracker
description: "Track income and expenses, see your live balance, and convert amounts between currencies — a fast, intuitive Flutter expense tracker."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  shared_preferences: ^2.5.3
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.7.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.1
  sqflite: ^2.3.3+1
  easy_localization: ^3.0.7
  fluttertoast: ^8.2.12
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  pretty_dio_logger: ^1.4.0
  go_router: ^15.1.0

  google_fonts: ^6.2.1
  image_picker: ^1.2.0
  lazy_load_scrollview: ^1.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mockito: ^5.5.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner:
dependency_overrides:
  win32: ^5.5.4


flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/

#    - assets/fonts/

#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/icons/inovola_logo.jpeg"
#  min_sdk_android: 25
#
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
